#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #


SwiftLizard:
  PHPCR:
    Jackrabbit:
      host: http://localhost:8080/server/
      jar: Resources/Java/JackRabbitServer/jackrabbit-standalone-2.4.1.jar
      workspaces:
        default:
          user: admin
          password: admin
