language: php

php:
  - 5.3
  - 5.4

before_script: 
  - wget -nc http://getcomposer.org/composer.phar
  - COMPOSER=./tests/jackalope-testing-composer.json php composer.phar install

script: phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
